server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: estonia13
    keyStoreType: PKCS12

spring:
  application:
    name: quest_creator
  
  datasource:
    url: 'jdbc:mysql://delta.mtw.ru/db_32026_1?prepareThreshold=0'
    username: user32026_1
    password: pwuser32026_1

logging:
  level:
    org.springframework: DEBUG