name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Установка JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Сборка с Maven
        run: mvn clean install

      - name: Запуск тестов
        run: mvn test

      - name: Логин в GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u savoook --password-stdin

      - name: Сборка Docker образа
        run: docker build -t ghcr.io/savoook/guest_creator:latest .

      - name: Публикация Docker образа
        run: docker push ghcr.io/savoook/guest_creator:latest